services:
  cache:
    image: redis:6-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - /docker/redis/cache:/data
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''