// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: directory/service.proto

package directory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DirectoryInfoServiceClient is the client API for DirectoryInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DirectoryInfoServiceClient interface {
	GetInformationForPath(ctx context.Context, in *DirectoryRequest, opts ...grpc.CallOption) (*DirectoryResponse, error)
}

type directoryInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDirectoryInfoServiceClient(cc grpc.ClientConnInterface) DirectoryInfoServiceClient {
	return &directoryInfoServiceClient{cc}
}

func (c *directoryInfoServiceClient) GetInformationForPath(ctx context.Context, in *DirectoryRequest, opts ...grpc.CallOption) (*DirectoryResponse, error) {
	out := new(DirectoryResponse)
	err := c.cc.Invoke(ctx, "/directory.service.DirectoryInfoService/GetInformationForPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirectoryInfoServiceServer is the server API for DirectoryInfoService service.
// All implementations must embed UnimplementedDirectoryInfoServiceServer
// for forward compatibility
type DirectoryInfoServiceServer interface {
	GetInformationForPath(context.Context, *DirectoryRequest) (*DirectoryResponse, error)
	mustEmbedUnimplementedDirectoryInfoServiceServer()
}

// UnimplementedDirectoryInfoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDirectoryInfoServiceServer struct {
}

func (UnimplementedDirectoryInfoServiceServer) GetInformationForPath(context.Context, *DirectoryRequest) (*DirectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInformationForPath not implemented")
}
func (UnimplementedDirectoryInfoServiceServer) mustEmbedUnimplementedDirectoryInfoServiceServer() {}

// UnsafeDirectoryInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DirectoryInfoServiceServer will
// result in compilation errors.
type UnsafeDirectoryInfoServiceServer interface {
	mustEmbedUnimplementedDirectoryInfoServiceServer()
}

func RegisterDirectoryInfoServiceServer(s grpc.ServiceRegistrar, srv DirectoryInfoServiceServer) {
	s.RegisterService(&DirectoryInfoService_ServiceDesc, srv)
}

func _DirectoryInfoService_GetInformationForPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryInfoServiceServer).GetInformationForPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/directory.service.DirectoryInfoService/GetInformationForPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryInfoServiceServer).GetInformationForPath(ctx, req.(*DirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DirectoryInfoService_ServiceDesc is the grpc.ServiceDesc for DirectoryInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DirectoryInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "directory.service.DirectoryInfoService",
	HandlerType: (*DirectoryInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInformationForPath",
			Handler:    _DirectoryInfoService_GetInformationForPath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "directory/service.proto",
}
